# Generated by Django 5.1.2 on 2025-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_developer_created_at_developer_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='content_guidelines',
            field=models.BooleanField(default=False, verbose_name='Content Guidelines'),
        ),
        migrations.AddField(
            model_name='developer',
            name='regulation_compliance',
            field=models.BooleanField(default=False, verbose_name='Regulation Compliance'),
        ),
        migrations.AddField(
            model_name='developer',
            name='security_requirements',
            field=models.BooleanField(default=False, verbose_name='Security Requirements'),
        ),
    ]
