# Generated by Django 5.1.2 on 2025-04-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_developer_content_guidelines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='content_guidelines',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='regulation_compliance',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='security_requirements',
        ),
    ]
