# Generated by Django 5.1.2 on 2025-04-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='content_guidelines',
            field=models.BooleanField(default=False, verbose_name='Content Guidelines'),
        ),
        migrations.AddField(
            model_name='app',
            name='regulation_compliance',
            field=models.BooleanField(default=False, verbose_name='Regulation Compliance'),
        ),
        migrations.AddField(
            model_name='app',
            name='security_requirements',
            field=models.BooleanField(default=False, verbose_name='Security Requirements'),
        ),
    ]
